### ISSUE TITLE
Error in waterwheel.js

### ISSUE THREAD

**Issue by capriosa** [contentacms/contenta_vue_nuxt#35]
After npm run dev I've get this error:
{ Error: Unknown error.
    at /Users/meinolfdroste/github-projects/druxt/node_modules/waterwheel/dist/waterwheel.js:1:5256
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  message: 'Unknown error.',
  status: 500,
  statusCode: 500,
  name: 'NuxtServerError' }

 ERROR

  Error: Unknown error.

  - waterwheel.js:1
    [druxt]/[waterwheel]/dist/waterwheel.js:1:5256

  - next_tick.js:160 process._tickCallback
    internal/process/next_tick.js:160:7

I have to change package.json of waterwheel to "main": "lib/waterwheel.js"
Now it works.

**Comment by nyl-auster** [comment]
oh thanks for pointing that. Not maintaining anymore this project anymore, is there a PR able to fix that on this repo or is it only on waterwheel side ?

**Comment by capriosa** [comment]
No maintainer anymore? :(
Fix ca be done in package.json:
"waterwheel": "1.3.6"

**Comment by nyl-auster** [comment]
@capriosa i pushed a new version, updating nuxt and fix deprecated warnings. I fixed waterwheel version to 1.3.6 (as you did) because 1.3.7 breaks, but i feel an issue might be opened on waterwheel side ?

looking for a new maintainer but no luck for now. Not doing Drupal anymore, but still think Nuxt.js + Headless Drupal is a very great combination ! I think i would try to use graphQL instead of JSONAPI today, depending on the state of graphQL modules.

**Comment by capriosa** [comment]
@nyl-auster There is already an issues on waterwheel.
